[snowflake]
SNOWFLAKE_ACCOUNT="KHIGKSW-TF63553"
SNOWFLAKE_USER="SNFLUSER2025"
SNOWFLAKE_PASSWORD="Superuser@2025"
SNOWFLAKE_WAREHOUSE="ETL_RUN_WH"
SNOWFLAKE_DATABASE="SNOWFLAKE_SAMPLE_DATA"
SNOWFLAKE_SCHEMA="TPCH_SF100"

[openai]
api_key = "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"
model   = "gpt-4o-mini"

[audit]
AUDIT_DB = "DATA_LOADS_DB"
AUDIT_SCHEMA  = "AUDIT_SCHEMA"
AUDIT_TABLE  = "CHAT_DATA_AUDIT"

